{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "ae9f055e-3179-45e8-a9cc-2bf13af2996e",
   "metadata": {
    "tags": []
   },
   "source": [
    "# Data Science Tools and Ecosystem\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "478b642f-d223-47ec-be29-a2187f4760a0",
   "metadata": {},
   "source": [
    "\n",
    "In this notebook, Data Science Tools and Ecosystem are summarized."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4868e26b-e91d-474a-bc8f-b8890e6ca0be",
   "metadata": {},
   "source": [
    "##Some of the popular languages that Data Scientists use are:\n",
    "1. sql\n",
    "2. python\n",
    "3. R"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1788e641-6fbc-4699-bf43-975ed56a90a1",
   "metadata": {},
   "source": [
    "\n",
    "##Some of the commonly used libraries used by Data Scientists include:\n",
    "1. pandas\n",
    "2. numpy\n",
    "3. matplotlib\n",
    "4. ggplot\n",
    "5. caret"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "af4ab079-7e3c-4cff-aaf8-874b0701e282",
   "metadata": {},
   "source": [
    "|Data Science Tools|\n",
    "|-----------|\n",
    "|RSTUDIO|\n",
    "|GITHUB|\n",
    "|Jupyter Notebooks|\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "af8d394e-45ff-44b0-a72d-5c8baa9977c8",
   "metadata": {},
   "source": [
    "###Below are a few examples of evaluating arithmetic expressions in Python"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "4b6cc1c1-00f5-48c0-b8dd-14add5dc51b9",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "17"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#This a simple arithmetic expression to mutiply then add integers\n",
    "(3*4)+5"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "736e61e2-88fc-4ae7-beca-6d09f775ff4d",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "3.3333333333333335"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# This will convert 200 minutes to hours by diving by 60\n",
    "200/60"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7387f955-eb0b-4dcc-aafc-43e34051ffef",
   "metadata": {},
   "source": [
    "#List popular languages for Data Science\n",
    "**Objectives:**\n",
    "* SQL\n",
    "* R\n",
    "* PYTHON\n",
    "* JULIA"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "40d206ba-48c1-49e8-95d9-170673dcc634",
   "metadata": {},
   "source": [
    "## Author\n",
    "AYA NABIL HELBAWY\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "48270250-c4e4-495c-adc7-d15518e9c502",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python",
   "language": "python",
   "name": "conda-env-python-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
